# Generated by Django 5.2.5 on 2025-09-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('supplierid', models.PositiveBigIntegerField()),
                ('categoryid', models.PositiveBigIntegerField()),
            ],
        ),
    ]
