# Generated by Django 5.2.5 on 2025-09-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('pid', models.PositiveBigIntegerField()),
                ('qty', models.PositiveBigIntegerField()),
                ('cid', models.CharField(max_length=4)),
                ('channel', models.PositiveBigIntegerField()),
            ],
        ),
    ]
