# Generated by Django 5.2.5 on 2025-09-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=64)),
                ('uname', models.CharField(max_length=64)),
            ],
        ),
    ]
