# Generated by Django 5.2.5 on 2025-09-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pwd',
            field=models.CharField(max_length=255),
        ),
    ]
